#! /bin/bash
echo "${BCyan}Enter your username:${Reset}"
read USER_NAME

if [[ -f `pwd`/functions ]]; then
  source functions
else
  echo "missing file: functions"
  exit 1
fi

echo "Running final commands to finish up installation"

user_chroot "source ~/.bashrc"
user_chroot "rbenv install 2.2.2"
user_chroot "rbenv global 2.2.2"

echo "gem: --no-ri --no-rdoc" > /mnt/home/${USER_NAME}/.gemrc
user_chroot "gem install bundler"

echo "Rbenv and Ruby Version:"
user_chroot "ruby -v"
echo "has been installed."
echo ""


# install rails
echo "Installing Ruby on Rails."
sleep 1
user_chroot "gem install rails -v 4.2.1"
user_chroot "rbenv rehash"
echo "Rails version: "
user_chroot "rails -v"
echo "has been installed."
echo ""

echo "Nodejs is being installed."
user_chroot "source ~/.bashrc"
user_chroot "nvm install stable"
user_chroot "nvm alias default stable"
user_chroot "nvm use default"
echo "Nodejs has been installed."
echo ""

echo "Basic install is complete!!"
read -p "Press [Enter] to exit and reboot.."
umount -R /mnt
reboot